#!/usr/local/bin/python

from os import system
from sys import argv

def build(yacc_file, lex_file):
    system("yacc -d {}".format(yacc_file))
    system("lex {}".format(lex_file))
    system("cc y.tab.c lex.yy.c")
    system("mv a.out tiny")

def clean():
    system("rm lex.yy.c y.tab.c y.tab.h tiny")

if __name__ == "__main__":
    if len(argv) == 2:
        if argv[1] == "clean":
            clean()
    elif len(argv) == 3:
        build(argv[1], argv[2])
    else:
        print "Usage: ./build <yacc file> <lex file> | clean"
