#!/usr/local/bin/python

from os import system
from sys import argv

def build():
    system("yacc -d tiny.yacc")
    system("lex tiny.lex")
    system("cc y.tab.c lex.yy.c")
    system("mv a.out tiny")

def clean():
    system("rm lex.yy.c y.tab.c y.tab.h tiny");

if __name__ == "__main__":
    if not (1 <= len(argv) <= 2):
        print "Usage: ./build [clean]"
    if len(argv) == 2:
        if argv[1] == "clean":
            clean()
    else:
        build()
